export const countries = [
  { value: "AF", option: "Afghanistan" },
  { value: "AX", option: "Åland Islands" },
  { value: "AL", option: "Albania" },
  { value: "DZ", option: "Algeria" },
  { value: "AS", option: "American Samoa" },
  { value: "AD", option: "Andorra" },
  { value: "AO", option: "Angola" },
  { value: "AI", option: "Anguilla" },
  { value: "AQ", option: "Antarctica" },
  { value: "AG", option: "Antigua and Barbuda" },
  { value: "AR", option: "Argentina" },
  { value: "AM", option: "Armenia" },
  { value: "AW", option: "Aruba" },
  { value: "AU", option: "Australia" },
  { value: "AT", option: "Austria" },
  { value: "AZ", option: "Azerbaijan" },
  { value: "BS", option: "Bahamas" },
  { value: "BH", option: "Bahrain" },
  { value: "BD", option: "Bangladesh" },
  { value: "BB", option: "Barbados" },
  { value: "BY", option: "Belarus" },
  { value: "BE", option: "Belgium" },
  { value: "BZ", option: "Belize" },
  { value: "BJ", option: "Benin" },
  { value: "BM", option: "Bermuda" },
  { value: "BT", option: "Bhutan" },
  { value: "BO", option: "Bolivia (Plurinational State of)" },
  { value: "BA", option: "Bosnia and Herzegovina" },
  { value: "BW", option: "Botswana" },
  { value: "BV", option: "Bouvet Island" },
  { value: "BR", option: "Brazil" },
  { value: "IO", option: "British Indian Ocean Territory" },
  { value: "BN", option: "Brunei Darussalam" },
  { value: "BG", option: "Bulgaria" },
  { value: "BF", option: "Burkina Faso" },
  { value: "BI", option: "Burundi" },
  { value: "CV", option: "Cabo Verde" },
  { value: "KH", option: "Cambodia" },
  { value: "CM", option: "Cameroon" },
  { value: "CA", option: "Canada" },
  { value: "BQ", option: "Caribbean Netherlands" },
  { value: "KY", option: "Cayman Islands" },
  { value: "CF", option: "Central African Republic" },
  { value: "TD", option: "Chad" },
  { value: "CL", option: "Chile" },
  { value: "CN", option: "China" },
  { value: "CX", option: "Christmas Island" },
  { value: "CC", option: "Cocos (Keeling) Islands" },
  { value: "CO", option: "Colombia" },
  { value: "KM", option: "Comoros" },
  { value: "CG", option: "Congo" },
  { value: "CD", option: "Congo, Democratic Republic of the" },
  { value: "CK", option: "Cook Islands" },
  { value: "CR", option: "Costa Rica" },
  { value: "HR", option: "Croatia" },
  { value: "CU", option: "Cuba" },
  { value: "CW", option: "Curaçao" },
  { value: "CY", option: "Cyprus" },
  { value: "CZ", option: "Czech Republic" },
  { value: "CI", option: "Côte d'Ivoire" },
  { value: "DK", option: "Denmark" },
  { value: "DJ", option: "Djibouti" },
  { value: "DM", option: "Dominica" },
  { value: "DO", option: "Dominican Republic" },
  { value: "EC", option: "Ecuador" },
  { value: "EG", option: "Egypt" },
  { value: "SV", option: "El Salvador" },
  { value: "GQ", option: "Equatorial Guinea" },
  { value: "ER", option: "Eritrea" },
  { value: "EE", option: "Estonia" },
  { value: "SZ", option: "Eswatini (Swaziland)" },
  { value: "ET", option: "Ethiopia" },
  { value: "FK", option: "Falkland Islands (Malvinas)" },
  { value: "FO", option: "Faroe Islands" },
  { value: "FJ", option: "Fiji" },
  { value: "FI", option: "Finland" },
  { value: "FR", option: "France" },
  { value: "GF", option: "French Guiana" },
  { value: "PF", option: "French Polynesia" },
  { value: "TF", option: "French Southern Territories" },
  { value: "GA", option: "Gabon" },
  { value: "GM", option: "Gambia" },
  { value: "GE", option: "Georgia" },
  { value: "DE", option: "Germany" },
  { value: "GH", option: "Ghana" },
  { value: "GI", option: "Gibraltar" },
  { value: "GR", option: "Greece" },
  { value: "GL", option: "Greenland" },
  { value: "GD", option: "Grenada" },
  { value: "GP", option: "Guadeloupe" },
  { value: "GU", option: "Guam" },
  { value: "GT", option: "Guatemala" },
  { value: "GG", option: "Guernsey" },
  { value: "GN", option: "Guinea" },
  { value: "GW", option: "Guinea-Bissau" },
  { value: "GY", option: "Guyana" },
  { value: "HT", option: "Haiti" },
  { value: "HM", option: "Heard Island and McDonald Islands" },
  { value: "HN", option: "Honduras" },
  { value: "HK", option: "Hong Kong" },
  { value: "HU", option: "Hungary" },
  { value: "IS", option: "Iceland" },
  { value: "IN", option: "India" },
  { value: "ID", option: "Indonesia" },
  { value: "IR", option: "Iran" },
  { value: "IQ", option: "Iraq" },
  { value: "IE", option: "Ireland" },
  { value: "IM", option: "Isle of Man" },
  { value: "IL", option: "Israel" },
  { value: "IT", option: "Italy" },
  { value: "JM", option: "Jamaica" },
  { value: "JP", option: "Japan" },
  { value: "JE", option: "Jersey" },
  { value: "JO", option: "Jordan" },
  { value: "KZ", option: "Kazakhstan" },
  { value: "KE", option: "Kenya" },
  { value: "KI", option: "Kiribati" },
  { value: "KP", option: "Korea, North" },
  { value: "KR", option: "Korea, South" },
  { value: "XK", option: "Kosovo" },
  { value: "KW", option: "Kuwait" },
  { value: "KG", option: "Kyrgyzstan" },
  { value: "LA", option: "Lao People's Democratic Republic" },
  { value: "LV", option: "Latvia" },
  { value: "LB", option: "Lebanon" },
  { value: "LS", option: "Lesotho" },
  { value: "LR", option: "Liberia" },
  { value: "LY", option: "Libya" },
  { value: "LI", option: "Liechtenstein" },
  { value: "LT", option: "Lithuania" },
  { value: "LU", option: "Luxembourg" },
  { value: "MO", option: "Macao" },
  { value: "MK", option: "North Macedonia" },
  { value: "MG", option: "Madagascar" },
  { value: "MW", option: "Malawi" },
  { value: "MY", option: "Malaysia" },
  { value: "MV", option: "Maldives" },
  { value: "ML", option: "Mali" },
  { value: "MT", option: "Malta" },
  { value: "MH", option: "Marshall Islands" },
  { value: "MQ", option: "Martinique" },
  { value: "MR", option: "Mauritania" },
  { value: "MU", option: "Mauritius" },
  { value: "YT", option: "Mayotte" },
  { value: "MX", option: "Mexico" },
  { value: "FM", option: "Micronesia" },
  { value: "MD", option: "Moldova" },
  { value: "MC", option: "Monaco" },
  { value: "MN", option: "Mongolia" },
  { value: "ME", option: "Montenegro" },
  { value: "MS", option: "Montserrat" },
  { value: "MA", option: "Morocco" },
  { value: "MZ", option: "Mozambique" },
  { value: "MM", option: "Myanmar (Burma)" },
  { value: "NA", option: "Namibia" },
  { value: "NR", option: "Nauru" },
  { value: "NP", option: "Nepal" },
  { value: "NL", option: "Netherlands" },
  { value: "AN", option: "Netherlands Antilles" },
  { value: "NC", option: "New Caledonia" },
  { value: "NZ", option: "New Zealand" },
  { value: "NI", option: "Nicaragua" },
  { value: "NE", option: "Niger" },
  { value: "NG", option: "Nigeria" },
  { value: "NU", option: "Niue" },
  { value: "NF", option: "Norfolk Island" },
  { value: "MP", option: "Northern Mariana Islands" },
  { value: "NO", option: "Norway" },
  { value: "OM", option: "Oman" },
  { value: "PK", option: "Pakistan" },
  { value: "PW", option: "Palau" },
  { value: "PS", option: "Palestine" },
  { value: "PA", option: "Panama" },
  { value: "PG", option: "Papua New Guinea" },
  { value: "PY", option: "Paraguay" },
  { value: "PE", option: "Peru" },
  { value: "PH", option: "Philippines" },
  { value: "PN", option: "Pitcairn Islands" },
  { value: "PL", option: "Poland" },
  { value: "PT", option: "Portugal" },
  { value: "PR", option: "Puerto Rico" },
  { value: "QA", option: "Qatar" },
  { value: "RE", option: "Réunion" },
  { value: "RO", option: "Romania" },
  { value: "RU", option: "Russian Federation" },
  { value: "RW", option: "Rwanda" },
  { value: "BL", option: "Saint Barthélemy" },
  { value: "SH", option: "Saint Helena" },
  { value: "KN", option: "Saint Kitts and Nevis" },
  { value: "LC", option: "Saint Lucia" },
  { value: "MF", option: "Saint Martin" },
  { value: "PM", option: "Saint Pierre and Miquelon" },
  { value: "VC", option: "Saint Vincent and the Grenadines" },
  { value: "WS", option: "Samoa" },
  { value: "SM", option: "San Marino" },
  { value: "ST", option: "Sao Tome and Principe" },
  { value: "SA", option: "Saudi Arabia" },
  { value: "SN", option: "Senegal" },
  { value: "RS", option: "Serbia" },
  { value: "SC", option: "Seychelles" },
  { value: "SL", option: "Sierra Leone" },
  { value: "SG", option: "Singapore" },
  { value: "SX", option: "Sint Maarten" },
  { value: "SK", option: "Slovakia" },
  { value: "SI", option: "Slovenia" },
  { value: "SB", option: "Solomon Islands" },
  { value: "SO", option: "Somalia" },
  { value: "ZA", option: "South Africa" },
  { value: "GS", option: "South Georgia and the South Sandwich Islands" },
  { value: "SS", option: "South Sudan" },
  { value: "ES", option: "Spain" },
  { value: "LK", option: "Sri Lanka" },
  { value: "SD", option: "Sudan" },
  { value: "SR", option: "Surioption" },
  { value: "SJ", option: "Svalbard and Jan Mayen" },
  { value: "SE", option: "Sweden" },
  { value: "CH", option: "Switzerland" },
  { value: "SY", option: "Syria" },
  { value: "TW", option: "Taiwan" },
  { value: "TJ", option: "Tajikistan" },
  { value: "TZ", option: "Tanzania" },
  { value: "TH", option: "Thailand" },
  { value: "TL", option: "Timor-Leste" },
  { value: "TG", option: "Togo" },
  { value: "TK", option: "Tokelau" },
  { value: "TO", option: "Tonga" },
  { value: "TT", option: "Trinidad and Tobago" },
  { value: "TN", option: "Tunisia" },
  { value: "TR", option: "Turkey (Türkiye)" },
  { value: "TM", option: "Turkmenistan" },
  { value: "TC", option: "Turks and Caicos Islands" },
  { value: "TV", option: "Tuvalu" },
  { value: "UG", option: "Uganda" },
  { value: "UA", option: "Ukraine" },
  { value: "AE", option: "United Arab Emirates" },
  { value: "GB", option: "United Kingdom" },
  { value: "US", option: "United States" },
  { value: "UY", option: "Uruguay" },
  { value: "UZ", option: "Uzbekistan" },
  { value: "VU", option: "Vanuatu" },
  { value: "VA", option: "Vatican City (Holy See)" },
  { value: "VE", option: "Venezuela" },
  { value: "VN", option: "Vietnam" },
  { value: "VG", option: "Virgin Islands, British" },
  { value: "VI", option: "Virgin Islands, U.S." },
  { value: "WF", option: "Wallis and Futuna" },
  { value: "EH", option: "Western Sahara" },
  { value: "YE", option: "Yemen" },
  { value: "ZM", option: "Zambia" },
  { value: "ZW", option: "Zimbabwe" }
];
